# -*- coding: utf-8 -*-
"""assignment1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dMthm9N9uCRtHWPYs84V8vsyq9CLuGfb
"""

from pygam import LinearGAM, s
import pandas as pd

train_url = 'https://raw.githubusercontent.com/dustywhite7/econ8310-assignment1/main/assignment_data_train.csv'
test_url = 'https://raw.githubusercontent.com/UNOBusinessForecasting/assignment-01-arima-gam-exponential-smoothing-ols-davis011235/refs/heads/main/assignment_data_test.csv'

data = pd.read_csv(train_url)
new_data = pd.read_csv(test_url)
new_data = new_data[['month', 'day', 'hour']]

x = data[['month', 'day', 'hour']]
y = data['trips']

model = LinearGAM(s(0) + s(1) + s(2))
modelFit = model.gridsearch(x.values, y)

pred = modelFit.predict(new_data)

print(pred[-20:])

