# -*- coding: utf-8 -*-
"""assignment1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dMthm9N9uCRtHWPYs84V8vsyq9CLuGfb
"""

import pandas as pd
import numpy as np
from pygam import LinearGAM, s
import matplotlib.pyplot as plt
import pickle

train_url = "https://github.com/dustywhite7/econ8310-assignment1/raw/main/assignment_data_train.csv"
train_data = pd.read_csv(train_url)

test_url = "https://github.com/dustywhite7/econ8310-assignment1/raw/main/assignment_data_test.csv"
test_data = pd.read_csv(test_url)

print(train_data)

X_train = train_data[['year', 'month', 'day', 'hour']]
y_train = train_data['trips']

X_test = test_data[['year', 'month', 'day', 'hour']]

model = LinearGAM(s(0) + s(1) + s(2) + s(3))
modelFit = model.fit(X_train, y_train)

pred = modelFit.predict(X_test)

test_data['predicted_trips'] = pred

print(test_data[['Timestamp', 'predicted_trips']])

